FROM node:latest as build
WORKDIR /usr/src/app
COPY package*.json ./
COPY tsconfig.json ./
RUN npm install
COPY src ./src
RUN npx tsc

FROM build
COPY ./src/index.ts ./src/index.ts
CMD node build/index.js 